picodata/genin

src/libs/ins/mod.rs, src/task.rs, src/task/args.rs, src/task/cluster/fs.rs, src/task/cluster/fs/test.rs, src/task/inv.rs
=> fix: issue 15, 16, 17

Cargo.lock, Cargo.toml, README.md, README.ru.md, src/task/args.rs
=> feat: update description and readme

.github/workflows/Build.yaml, Makefile, build/el7/genin.x86_64.spec, build/el8/genin.x86_64.spec
=> fix: make genin executable by default

.github/workflows/Build.yaml, .github/workflows/IntegrationTest.yaml, .github/workflows/Release.yaml, .github/workflows/UnitTest.yaml
=> 52 improve ci

.github/workflows/Build.yaml, .github/workflows/UnitTest.yaml
=> fix: add template to master branch name variable

Cargo.lock, Cargo.toml, src/task.rs, src/task/args.rs, src/task/cluster/fs.rs, src/task/cluster/fs/test.rs, src/task/flv.rs, src/task/flv/test.rs
=> feat: migrate to clap v4

src/task/cluster/hst/v2.rs, src/task/inventory/test.rs
=> fix: binary port in advertise uri

Cargo.lock, Cargo.toml, README.md, README.ru.md, deploy/ansible/cluster.genin.yml, test/resources/test-big-cluster.genin.yaml, test/resources/test-cluster-uncomplete.genin.yaml, test/resources/test-cluster.genin.yaml, test/resources/test-giant-cluster.genin.yaml, test/resources/test-selectel.genin.yaml
=> feat: remove selectel mentions

Cargo.lock, Cargo.toml, README.md, README.ru.md, src/error.rs, src/task.rs, src/task/args.rs, src/task/cluster.rs, src/task/cluster/fs.rs, src/task/cluster/hst/v2.rs, src/task/cluster/test.rs, src/task/flv.rs, src/task/inventory.rs
=> feat: upgrade command and EN readme

Cargo.lock, Cargo.toml, README.md, README.ru.md, src/main.rs, src/task/cluster.rs, src/task/cluster/hst.rs, src/task/cluster/hst/test.rs, src/task/cluster/hst/v2.rs, src/task/cluster/hst/view.rs, src/task/cluster/ins.rs, src/task/cluster/ins/v2.rs, src/task/cluster/name.rs, src/task/cluster/test.rs, src/task/cluster/topology.rs, src/task/cluster/topology/test.rs, src/task/flv.rs, src/task/inventory.rs
=> feat: new colored output

src/task/cluster.rs, src/task/cluster/hst/test.rs, src/task/cluster/hst/v2.rs, src/task/cluster/ins/v2.rs, src/task/cluster/topology.rs, src/task/cluster/topology/test.rs, src/task/inventory.rs, src/task/inventory/test.rs
=> feat: add vars to topolgy sets

Cargo.lock, Cargo.toml, README.md, README.ru.md, src/task/cluster/ins/v2.rs, src/task/cluster/topology.rs, src/task/inventory/test.rs, test/resources/test-2-new-cluster.genin.yaml
=> feat: all-rw feature

.gitignore, Cargo.lock, Cargo.toml, README.md, README.ru.md, src/error.rs, src/task.rs, src/task/args.rs, src/task/cluster.rs, src/task/cluster/fs.rs, src/task/cluster/hst/v2.rs, src/task/cluster/ins/test.rs, src/task/cluster/test.rs, src/task/cluster/topology.rs, src/task/cluster/topology/test.rs, src/task/flv.rs, src/task/inventory.rs, src/task/serde_genin.rs
=> feat: major error improvement

README.md, README.ru.md
=> fix: add vshard group example

Cargo.lock, Cargo.toml, README.md, README.ru.md
=> feat: update version

Cargo.lock, Cargo.toml, README.md, README.ru.md, src/task.rs, src/task/cluster.rs, src/task/cluster/fs.rs, src/task/cluster/test.rs, src/task/cluster/topology/test.rs, src/task/serde_genin.rs
=> 97 special placeholders

.gitignore, Cargo.lock, Cargo.toml, LICENSE, README.md, README.ru.md, docs/examples/cluster.genin.yml, docs/examples/fd-cluster.genin.yml, docs/examples/tdg-cluster.genin.yaml, src/task.rs, src/task/inventory.rs
=> feat: minor fixes and docs update

src/task.rs, src/task/cluster/fs.rs
=> fix: subdirs paths

Cargo.lock, Cargo.toml, README.md, README.ru.md, src/task/flv.rs, src/task/flv/test.rs
=> feat: fix stateboard uri as dns name

src/task.rs, src/task/args.rs, src/task/cluster.rs, src/task/cluster/hst/snapshots/genin__task__cluster__hst__test__merge_with_decreasing_hosts.snap, src/task/cluster/hst/test.rs, src/task/cluster/hst/v2.rs, src/task/cluster/name.rs, src/task/cluster/snapshots/genin__task__cluster__test__upgrade_with_same_name.snap, src/task/cluster/test.rs
=> feat: new option idiomatic-merge

Cargo.lock, Cargo.toml, README.md, README.ru.md, docs/RELEASE.ru.md
=> release 0.5.6 version

src/task.rs, src/task/args.rs, src/task/cluster.rs, src/task/cluster/ins/v2.rs, src/task/inventory.rs
Previously, it was only available for build command
=> add --fd-as-zone flag for upgrade command

src/task/cluster.rs, src/task/cluster/name.rs, src/task/cluster/name/test.rs, tests/mod.rs, tests/resources/names/cluster-underscore1.genin.yml, tests/resources/names/cluster-underscore2.genin.yml, tests/snapshots/r#mod__undescrore_names.snap, tests/snapshots/r#mod__undescrore_names_remove.snap
=> Fix incorrect role distribution when using underscore in names

.github/workflows/Release.yaml, configs/cluster.genin.yml, src/task/cluster/snapshots/genin__task__cluster__test__cluster_v2_from_args.snap, src/task/cluster/snapshots/genin__task__cluster__test__cluster_v2_from_inventory.snap, src/task/cluster/snapshots/genin__task__cluster__test__default_cluster.snap, src/task/cluster/topology.rs, src/task/cluster/topology/test.rs, tests/snapshots/r#mod__genin_init.snap, tests/snapshots/r#mod__init_with_comments.snap
=> Add alias replicaset_count for replicasets_count

Cargo.lock, Cargo.toml, src/task.rs, src/task/args.rs, tests/mod.rs
=> Add confirm on build with state
